<?php

/**
 * @file
 * This module holds an exercise for learning Drupal module development as
 * taught during the Wayne Eaker's DrupalTutor course. Please contribute!
 */

/**
 * Implements hook_block_info().
 */
function hello_block_info() {
  $blocks = array();
  
  $blocks['hello_world'] = array(
    'info' => t('Hello world block'),
  );
  
  $blocks['hello_user'] = array(
    'info' => t('Hellow User Block'),
  );
  
  $blocks['user_info'] = array(
    'info' => t('User info block'),
  );
    
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function hello_block_view($delta = '') {
  $block = array();
  
  switch ($delta) {
    case 'hello_world':
      $block['subject'] = t('Hello World!!!');
      $block['content'] = t('This is the hello world block.');
      break;
    
    case 'hello_user':
      $current_hour = date('G');

      $greeting = '';
      if ($current_hour < 12) {
        $greeting = 'Good morning@user_name!';
      }
      elseif ($current_hour < 18) {
        $greeting = 'Good afternoon@user_name!';
      }
      elseif ($current_hour >= 18) {
        $greeting = 'Good evening@user_name!';
      }
      else {
        $greeting = 'Hello@user_name!!';
      }
      
      $block['subject'] = t('Hello User!!!');
      // Both of the following are functionally equivalent, but the second one
      // may be more preferred due to maintainability.
      // global $user;
      // $block['content'] = t($greeting, array('@user_name' => $user->name));
      $user_name = '';
      if (!empty($GLOBALS['user']->name)) {
        $user_name = ' ' . $GLOBALS['user']->name;
      }
      $block['content'] = t($greeting, array('@user_name' => $user_name));
      break;
      
    case 'user_info':
      if (arg(0) == 'user' && is_numeric(arg(1))) {
        $account = user_load(arg(1));
        
        if (!empty($account)) {
          $block['subject'] = t('User Info');
          
          $content = '';
          $content .= '<div><label>' . t('Name') . '</label>' . $account->name . '</div>';
          $content .= '<div><label>' . t('Mail') . '</label>' . $account->mail . '</div>';
          $content .= '<div><label>' . t('Created') . '</label>' . format_date($account->created) . '</div>';
          $content .= '<div><label>' . t('Last Access') . '</label>';
          $content .= $account->access == 0 ? t('never') : format_date($account->access);
          $content .= '</div>';
          
          $block['content'] = $content;
        }
      }
      break;
    
    default: 
      break;
  }
  
  return $block;
}