<?php

/**
 * @file
 * This module holds an exercise for learning Drupal module development as
 * taught during the Wayne Eaker's DrupalTutor course. Please contribute!
 */

/**
 * Implements hook_block_info().
 */
function hello_block_info() {
  $blocks = array();
  
  $blocks['hello_world'] = array(
    'info' => t('Hello World Block'),
  );
  
  $blocks['hello_user'] = array(
    'info' => t('Hellow User Block'),
  );
    
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function hello_block_view($delta = '') {
  kpr($delta);
  $block = array();
  
  switch ($delta) {
    case 'hello_world':
      $block['subject'] = t('Hello World!!!');
      $block['content'] = t('This is the hello world block.');
      break;
    
    case 'hello_user':
      $current_hour = date('G');
      $greeting = '';
      if ($current_hour < 12) {
        $greeting = 'Good morning @user_name!';
      }
      elseif ($current_hour < 18) {
        $greeting = 'Good evening @user_name!';
      }
      elseif ($current_hour >= 18) {
        $greeting = 'Good evening @user_name!';
      }
      else {
        $greeting = 'Hello @user_name!!';
      }
      
      $block['subject'] = t('Hello World!!!');
      // Both of the following are functionally equivalent, but the second one
      // may be more preferred due to maintainability.
      // global $user;
      // $block['content'] = t($greeting, array('@user_name' => $user->name));
      $block['content'] = t($greeting, array('@user_name' => $GLOBALS['user']->name));
      break;
    
    default: 
      break;
  }
  
  return $block;
}